title: Your Turn To Die українською
description: Your Turn To Die — це візуальна новела/пригодницька гра від Nankidai про смертельну гру, де учасники вибирають, хто помре. (Неофіційний переклад українською мовою)